apps:
  api:
    name: "gosmic/api"
    version: "1.0.0"
    listener:
      host: "0.0.0.0"
      port: 5080
    ssl:
      enabled: false
      cert: ""
      key: ""
      manager:
        email: "anar.k.jafarov@gmail.com"
        host_whitelist: ["gosmic.io"]
        cache_dir: ".cache/tls"

database: # uses mongodb
  connection_string: "mongodb://localhost:27017"
  database_name: "gosmic"
  #connection_string: "mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]"
  #database_name: "gosmic"

storage:
  root: "/storage/gosmic"
  pbfs: "/storage/gosmic/pbfs"

osm:
  sources:
    pbf:
      url: "https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf"
      file: "planet-latest.osm.pbf"