apps:
  api:
    name: "gosmic/api"
    version: "1.0.0"
    listener:
      host: "0.0.0.0"
      port: 5080
    ssl:
      enabled: false
      cert: ""
      key: ""
      manager:
        email: "anar.k.jafarov@gmail.com"
        host_whitelist: ["gosmic.io"]
        cache_dir: ".cache/tls"

database: # uses mongodb
  connection_string: "mongodb://localhost:27017"
  database_name: "gosmic"
  #connection_string: "mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]"
  #database_name: "gosmic"

storage:
  root: "/storage/gosmic"
  pbfs: "/storage/gosmic/pbfs"

osm:
  sources:
    pbfs:
      - region: "Europe"
        url: "https://download.geofabrik.de/europe-latest.osm.pbf"
        file: "europe-latest.osm.pbf"
      - region: "Africa"
        url: "https://download.geofabrik.de/africa-latest.osm.pbf"
        file: "africa-latest.osm.pbf"
      - region: "Asia"
        url: "https://download.geofabrik.de/asia-latest.osm.pbf"
        file: "asia-latest.osm.pbf"
      - region: "Australia and Oceania"
        url: "https://download.geofabrik.de/australia-oceania-latest.osm.pbf"
        file: "australia-oceania-latest.osm.pbf"
      - region: "North America"
        url: "https://download.geofabrik.de/north-america-latest.osm.pbf"
        file: "north-america-latest.osm.pbf"
      - region: "Central America"
        url: "https://download.geofabrik.de/central-america-latest.osm.pbf"
        file: "central-america-latest.osm.pbf"
      - region: "South America"
        url: "https://download.geofabrik.de/south-america-latest.osm.pbf"
        file: "south-america-latest.osm.pbf"
      - region: "Antarctica"
        url: "https://download.geofabrik.de/antarctica-latest.osm.pbf"
        file: "antarctica-latest.osm.pbf"
